// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmzphkUgVxtppqMZy2Fgrpz1fDLqCIABA',
    appId: '1:534866688100:web:d4d5ffdcb595e715a9c771',
    messagingSenderId: '534866688100',
    projectId: 'smart-itinerary-planner-d2d88',
    authDomain: 'smart-itinerary-planner-d2d88.firebaseapp.com',
    storageBucket: 'smart-itinerary-planner-d2d88.firebasestorage.app',
    measurementId: 'G-G2VYPFS58S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoylWXFH97_EJoDuaa1YmYmPz6zb99AFI',
    appId: '1:534866688100:android:7d5e5f608f94b91ea9c771',
    messagingSenderId: '534866688100',
    projectId: 'smart-itinerary-planner-d2d88',
    storageBucket: 'smart-itinerary-planner-d2d88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs_wFSAvudl2Kh2bA9C3i1bceT-jHddHk',
    appId: '1:534866688100:ios:413f0429c5c160e8a9c771',
    messagingSenderId: '534866688100',
    projectId: 'smart-itinerary-planner-d2d88',
    storageBucket: 'smart-itinerary-planner-d2d88.firebasestorage.app',
    iosClientId: '534866688100-qokmi3fcbvr17tnapsq55u1a7lgh8jt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartItineraryPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs_wFSAvudl2Kh2bA9C3i1bceT-jHddHk',
    appId: '1:534866688100:ios:413f0429c5c160e8a9c771',
    messagingSenderId: '534866688100',
    projectId: 'smart-itinerary-planner-d2d88',
    storageBucket: 'smart-itinerary-planner-d2d88.firebasestorage.app',
    iosClientId: '534866688100-qokmi3fcbvr17tnapsq55u1a7lgh8jt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartItineraryPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmzphkUgVxtppqMZy2Fgrpz1fDLqCIABA',
    appId: '1:534866688100:web:0dd75b73703bfbbaa9c771',
    messagingSenderId: '534866688100',
    projectId: 'smart-itinerary-planner-d2d88',
    authDomain: 'smart-itinerary-planner-d2d88.firebaseapp.com',
    storageBucket: 'smart-itinerary-planner-d2d88.firebasestorage.app',
    measurementId: 'G-PQMB56LC2Z',
  );
}
